name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  build-zip:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip project files
        run: zip -r release.zip src

      - name: Extract version from manifest.json
        id: extract_version
        shell: bash
        run: |
          version=$(jq -r .version src/manifest.json)
          echo "version=$version" >> $GITHUB_ENV

      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-zip
          path: release.zip

  upload-chrome-extension:
    needs: build-zip
    runs-on: ubuntu-latest

    steps:
      - name: Download ZIP artifact
        uses: actions/download-artifact@v2
        with:
          name: release-zip

      - name: Upload Chrome extension
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: release.zip
          extension-id: decpnblgkebmgfadljfngondjdiaaafp
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}

  create-tag-and-release:
    needs: upload-chrome-extension
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build-zip.outputs.version }}
          release_name: Release ${{ needs.build-zip.outputs.version }}
          draft: false
          prerelease: false
