name: Zip Release

on:
  push:
    branches:
      - main # 或者您用于发布的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip project files excluding some
        run: zip -r release.zip . -x "*.git*"

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: release.zip
